### ISSUE TITLE
Map ESC to keyboard-quit for FZF window?

### ISSUE THREAD

**Issue by jkrmr** [bling/fzf.el#10]
Apologies for the noob question, but is there a way to have ESC close the FZF window, I've been trying to define something like the following:

```elisp
(add-hook 'fzf-mode-hook (lambda ()
  (define-key fzf-mode-map (kbd "ESC") 'keyboard-quit))
```

But from the source code it doesn't look like there's anything like an FZF mode to hook into. Is that right? If so, is there something else I could hook into?

Thanks in advance!

**Comment by bling** [comment]
`(term-char-mode)` is the magic that makes everything work, however it does it by intercepting everything you type, so look into the code there to see if it provides anything.

**Comment by jkrmr** [comment]
thanks! I appreciate it 😄
