### ISSUE TITLE
Specifying absolute path to fzf in `fzf/executable' results in "Wrong type argument: processp, nil"

### ISSUE THREAD

**Issue by JohnC32** [bling/fzf.el#105]
If fzf is not on the path and you specify `fzf/executable` as the full path to the executable, running `M-x fzf` will result in error:

     Wrong type argument: processp, nil
     Back to top level
     Error in post-command-hook (term-goto-process-mark-maybe): (wrong-type-argument processp nil)

This is on Debian 11, using Emacs 27 with fzf.el from Jan 13, 2023,  1d80e76.

**Comment by pierre-rouleau** [comment]
I concur. There's a problem there. I'm looking at it.

**Comment by pierre-rouleau** [comment]
@JohnC32 Thanks for reporting this.  It'd be great if you could try the fix in my PR and confirm it works for you.

**Comment by JohnC32** [comment]
Thanks for the quick fix. The fix works.

**Comment by pierre-rouleau** [comment]
I just happened to look at my messages last night.  Thanks for confirming.   I Just asked @bling to integrate it.
