### ISSUE TITLE
What's the beautiful font you're using on the front page?

### ISSUE THREAD

**Issue by blais** [bling/fzf.el#111]
From this image?
https://cloud.githubusercontent.com/assets/306502/12380684/ca0a6648-bd46-11e5-9091-841b282874e4.gif
Just curious.  (I like M+1m, but this seems like a good alternative.)
Thank you,

**Comment by domsch1988** [comment]
Looks like Jet Brains Mono to me.

**Comment by blais** [comment]
I just installed it and I would agree. 
In its larger sizes it looks like that indeed (but smaller somehow not as nice).
I can't quite find a way to make it be as condensed as my other font.
It's nice to be able to compare them.

Thank you,
