### ISSUE TITLE
Progress counter is taking a new line for each update

### ISSUE THREAD

**Issue by vishesh** [bling/fzf.el#18]
I'm trying to setup FZF on my GNU Emacs 25.1.1  installed os MacOS Sierra. What I get can be seen in the screenshot below. My config works fine on my linux machine.

<img width="628" alt="screen shot 2017-03-15 at 4 25 05 pm" src="https://cloud.githubusercontent.com/assets/310099/23975045/ddf46800-099b-11e7-9189-b5e6fc733f33.png">

**Comment by leourbina** [comment]
I'm seeing the same thing:

![fzf-broken](https://cloud.githubusercontent.com/assets/434020/25073946/71f7e3f6-22bf-11e7-8c99-82013a837c02.gif)

**Comment by leourbina** [comment]
@vishesh I was able to get it to work by downgrading to fzf version 0.15.9. Prior to this I was running 0.16.6.

**Comment by Nephyrin** [comment]
Adjusting fzf margins seems to work around this, I think it's because it is emitting lines larger than the terminal? Might be dependent on window size or other factors.

`(setq fzf/args "--no-hscroll --margin=0,1,1,0")`
