### ISSUE TITLE
Path is not stripped correctly when directory does not end with '/'

### ISSUE THREAD

**Issue by jacobdufault** [bling/fzf.el#4]
If `default-directory` is set to `/work/chrome/src`, then files will fail to open because [file](https://github.com/bling/fzf.el/blob/master/fzf.el#L66) will get set to `/work/chrome/src/src/*`. Setting `default-directory` to `/work/chrome/src/` (notice the trailing slash) fixes things.

**Comment by bling** [comment]
we could put a check for the trailing slash, but directories in emacs should *always* end in a slash, otherwise bad things happen...
