### ISSUE TITLE
fzf is not working when not in project directory.

### ISSUE THREAD

**Issue by tttuuu888** [bling/fzf.el#42]
When not in project directory, M-x fzf  shows below error.

Wrong type argument: stringp, nil

I thinks this is due to recent update of projectile-project-root function.([projectile issue 1304](https://github.com/bbatsov/projectile/issues/1304))

My fzf version is fzf-20180619.145

**Comment by tttuuu888** [comment]
Well, I didn't mention this, but of course this is the case when user has installed latest projectile package.
If we need to consider compatibility for older version of projectile, we may need another solution though.

**Comment by benneti** [comment]
can confirm that the PR fixes this issue for me
