### ISSUE TITLE
Turn off evil?

### ISSUE THREAD

**Issue by neojski** [bling/fzf.el#48]
I think it relates to #45 a bit.

I would like fzf to turn-off evil mode in the fzf window so that I could use ctrl-p and ctrl-n to move up and down rather than trying to autocomplete. I made the change locally by adding `(turn-off-evil-mode)` [here](https://github.com/bling/fzf.el/blob/521d18933cb586337c4e34281bdc71ac07202c98/fzf.el#L125). Would you accept such change as a PR? Or, maybe, it should be configurable?

**Comment by j-cr** [comment]
```
(advice-add 'fzf :after 'turn-off-evil-mode)
(advice-add 'fzf-git :after 'turn-off-evil-mode)
(advice-add 'fzf-git-grep :after 'turn-off-evil-mode)
(advice-add 'fzf-git-files :after 'turn-off-evil-mode)
(advice-add 'fzf-hg :after 'turn-off-evil-mode)
(advice-add 'fzf-directory :after 'turn-off-evil-mode)
(advice-add 'fzf-projectile :after 'turn-off-evil-mode)
```
