### ISSUE TITLE
fzf for buffers?

### ISSUE THREAD

**Issue by schmeisers** [bling/fzf.el#50]
It would be great to have a fzf-buffers command that lets a user choose buffers through the fzf interface.

**Comment by neojski** [comment]
You can try swiper: https://github.com/abo-abo/swiper. It's not exactly fzf but it's well integrated with a lot of commands. You probably want <kbd>(ivy-switch-buffer)</kbd>.

**Comment by bling** [comment]
yea, stuff like buffers are better done with other packages like ido, helm, swiper.
