### ISSUE TITLE
fzf-git-files not visiting file after making selection

### ISSUE THREAD

**Issue by anschwa** [bling/fzf.el#59]
I'm using Emacs 27.1 and fzf 0.22.0 on macOS 10.15.7.

When I run `fzf-git-files` from graphical emacs, I can see a list of project files, but making a selection brings me back to the same buffer without visiting a new file.

However, when I use `fzf-git-grep` I am able to successfully visit a file after making a selection.

This doesn't appear to be an issue when I connect to emacs from Terminal.app.

I also tried installing emacs 26.3, but had the same problem.

**Comment by alexanderjamesking** [comment]
I noticed this too and fixed it locally, assuming it's the same issue as mine it was due to whitespace after the filename. I was about to raise a PR but there is one already: https://github.com/bling/fzf.el/pull/56
