### ISSUE TITLE
fzf show only files in a directory where fzf/executable located

### ISSUE THREAD

**Issue by tttuuu888** [bling/fzf.el#64]
Since recent update, `fzf` shows only files in a directory where fzf/executable located. Thanks.

**Comment by samclearman** [comment]
https://github.com/bling/fzf.el/pull/65 should fix

**Comment by tttuuu888** [comment]
@samclearman Thank you for your work and feedback. It seems like if I run `M-x fzf` in the directory which is not a project root(e.g. home directory), the result is files of /usr/bin/ directory. The result is files like cat, ls, grep etc.  I thought my `fzf` is locaed in /usr/bin but it wasn't. Maybe it's the directory where emacs executable file is located. Thanks.

**Comment by f6p** [comment]
I confirm the case, but as I don't have projectile installed it also happens inside project directories (like git etc). This seems somehow related to `fzf/resolve-directory` which was introduced in #63.
