### ISSUE TITLE
Configurable window split position

### ISSUE THREAD

**Issue by romanoaugusto88** [bling/fzf.el#7]
I mean a defcustom controlling where it will appears(top or bottom for now).
top by default and with `--reverse` arg would be possible to display the * fzf * buffer on bottom.

What do you think, @bling ?

**Comment by phcostabh** [comment]
:+1:

**Comment by dubiousdavid** [comment]
My fork has a nice fix for this issue: https://github.com/dubiousdavid/fzf.el/blob/master/fzf.el

**Comment by bling** [comment]
certainly open to PRs!

**Comment by denisinla** [comment]
@dubiousdavid PR your change for bottom positioning for fzf. I've been using your fork for a few weeks already without an issue on my end.

**Comment by dubiousdavid** [comment]
@bling This issue should be closed. Also, I believe a new release needs to be cut.
