### ISSUE TITLE
fzf.el does not work since recent fzf update

### ISSUE THREAD

**Issue by tttuuu888** [bling/fzf.el#82]
Hello,
Since latest fzf update(0.35.1), fzf.el doesn't work.
When I choose a file, it just exits without anything happens.
Thanks.

**Comment by tttuuu888** [comment]
This issue appears to be related to a separator line newly added to fzf.
A temporary Workaround for the issue is adding "--no-separator" to `fzf/args`.

 `(setq fzf/args (concat fzf/args " --no-separator"))`

Thanks.

**Comment by pierre-rouleau** [comment]
@tttuuu888 I ran into this issue as well.  See my issue https://github.com/bling/fzf.el/issues/84 which I resolved without preventing the fzf separator.  Both solutions could be applied for increased reliability.

**Comment by pierre-rouleau** [comment]
with the latest changes merged in this should also be fixed.

**Comment by tttuuu888** [comment]
@pierre-rouleau I've confirmed that the issue is resolved. Thank you so much. I will close the issue.
